### ISSUE TITLE
Cannot dump any table containing localized data

### ISSUE THREAD

**Issue by Artefact2** [DarkFenX/Phobos#4]
After the Scylla update:

Without `-t` argument:

      processing invtypes
        failed to fetch data - ContainerNameError: container "res/localization/localization_main" is not available for miner StuffedPickleMiner

With `-t en-us`:

      processing billtypes
        failed to fetch data - LanguageNotAvailable: data for language "en-us" cannot be loaded

**Comment by DarkFenX** [comment]
Use singularity phobos branch and https://github.com/DarkFenX/reverence for now.

Proper update will be released as soon as Entity updates reverence.
